<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Enrollment extends Model
{
    use HasFactory, SoftDeletes;
    
    protected $guarded = ['id'];
    
    protected $casts = [
        'enrollment_date' => 'datetime',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function course(): BelongsTo
    {
        return $this->belongsTo(Course::class);
    }

    public function coupon(): BelongsTo
    {
        return $this->belongsTo(Coupon::class);
    }

    public function transactions(): HasMany
    {
        return $this->hasMany(Transaction::class);
    }
    
    /**
     * Get quiz sessions associated with this enrollment
     */
    public function quizSessions(): HasMany
    {
        return $this->hasMany(QuizSession::class);
    }
    
    /**
     * Get exam sessions associated with this enrollment
     */
    public function examSessions(): HasMany
    {
        return $this->hasMany(ExamSession::class);
    }
    
    /**
     * Get revenue generated by this enrollment
     */
    public function revenue(): HasMany
    {
        return $this->hasMany(Revenue::class);
    }
}
